export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_PROGRESS = 'SEARCH_PROGRESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const SEARCH_INIT = 'SEARCH_INIT';
export const SET_SEARCH_TRIES = 'SET_SEARCH_TRIES';
export const CLEAR_SEARCH_ERRORS = 'CLEAR_SEARCH_ERRORS';